# =============================================================================
# Platforma Helm Chart Configuration
# =============================================================================

# -- Number of replicas for the deployment
replicaCount: 1

# -- Image configuration
image:
  repository: europe-west3-docker.pkg.dev/mik8s-euwe3-prod-gke-project/pl/pl
  pullPolicy: Always
  tag: "main" # or Chart.AppVersion

docker:
  enabled: false
  resources:
    limits:
      cpu: 4
      memory: 8Gi

serviceAccount:
  create: false
  name: "platforma-sa"
  annotations: {}

service:
  type: LoadBalancer # ClusterIP, NodePort, LoadBalancer
  port: 6345 # Matches --listen-port default
  annotations:
    external-dns.alpha.kubernetes.io/hostname: pl3.gcp.milaboratories.com

env:
  # variables: []

  secretVariables:
    - name: PL_LICENSE
      secretKeyRef:
        name: pl-license-secret
        key: pl-license-key

  # configMapVariables: []

deployment:
  securityContext:
    runAsUser: 1010 # Run as root user inside the container
    runAsGroup: 1010 # Run as root group inside the container
    runAsNonRoot: true # Allow running as root user
    capabilities:
      add: []
      drop: ["ALL"]
  podSecurityContext:
    fsGroup: 1010 # Group ID for volume ownership

persistence:
  mainRoot:
    enabled: false

  dbDir:
    enabled: true
    storageClass: "standard-rwo"
    mountPath: /data/rocksdb

listenOptions:
  port: 6345
  httpPort: 6347

gcp:
  serviceAccount: "mik8s-platforma-access@mik8s-euwe3-prod-gke-project.iam.gserviceaccount.com"
  projectId: "mik8s-euwe3-prod-gke-project"

primaryStorage:
  gcs:
    enabled: true
    url: "gs://mik8s-platforma-euwe3-prod-gke/platforma-primary-pl3/" # e.g., gs://<bucket>[/<prefix-in-bucket>]

dataLibrary:
  gcs:
    - id: "library"
      enabled: true
      url: "gs://mik8s-platforma-library-euwe3-prod-gke/"
    - id: "test-assets"
      enabled: true
      url: "gs://mik8s-platforma-euwe3-prod-gke/test-assets/"

authOptions:
  ldap:
    enabled: true
    server: "ldap://pl0-glauth.prod-pl0.svc.cluster.local:3893"
    dn: "cn=%u,ou=users,ou=users,dc=pldemo,dc=io"

extraArgs:
  - --auth-sessions-gen=1
  - --skip-extended-self-check
  - --keep-faulty-workdirs=16h
  - --assets-registry-url=https://mik8s-assets-sync-euwe3-prod-gke.storage.googleapis.com/
  - --log-component-level=batch.driver.commands=debug
  - --log-component-level=local.driver.commands=debug
  - --runner-enable-docker
  - --queue-runner=ui-tasks:local
  - --queue-runner=light:google-batch
  - --queue-runner=medium:google-batch
  - --queue-runner=heavy:google-batch

# -- Google Batch Options (--google-batch-storage, --google-batch-project, --google-batch-region, --google-batch-job-name-prefix, --google-batch-job-image, --google-batch-network, --google-batch-subnetwork, --google-batch-provisioning)
googleBatch:
  enabled: true
  region: "europe-west3"
  jobNamePrefix: "pl3"
  jobImage: ""
  network: "projects/mik8s-euwe3-prod-gke-project/global/networks/mik8s-euwe3-prod-gke-vpc"
  subnetwork: "projects/mik8s-euwe3-prod-gke-project/regions/europe-west3/subnetworks/mik8s-euwe3-prod-gke-private-1"
  provisioning: "STANDARD"

  storage: "/data/nfs=nfs://10.244.108.130/nfs_share"
  volumes:
    enabled: true
    name: "nfs-volume"
    mountPath: "/data/nfs"
    workDirName: "pl3/work"
    packagesDirName: "pl3/packages"
    existingClaim: "filestore-fast-pvc"
    size: "1Ti"
    accessMode: "ReadWriteMany"

logging:
  destination: "dir:///data/nfs/pl3/logs"
  #destination: "stream://stdout"

  persistence:
    enabled: false
    size: 5Gi
    mountPath: "/var/log/platforma"

monitoring:
  enabled: true
  podMonitoring:
    enabled: true

debug:
  enabled: true

# -- Resource limits and requests
resources:
  limits:
    cpu: 8000m
    memory: 16Gi
  requests:
    cpu: 4000m
    memory: 8Gi

# Toleration - allows pod to schedule on tainted nodes
tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "large"
    effect: "NoSchedule"

# Affinity - ensures pod schedules ONLY on large-pool nodes
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: "node.milab.io/pool"
              operator: "In"
              values:
                - "large"
