#
# NOTE: this values.yaml is for dev-common GKE instance used by backend team.
#
# How to use:
#   helm upgrade --install "dev-common" platforma/platforma --values values-dev-gcloud.yaml --namespace dev-gke
#

docker:
  enabled: true
  resources:
    limits:
      cpu: 8
      memory: 16Gi

image:
  repository: europe-west3-docker.pkg.dev/mik8s-euwe3-prod-gke-project/pl/pl
  pullPolicy: Always
  tag: "1.45.3-357-1598-merge" # or Chart.AppVersion

serviceAccount:
  create: false
  name: "platforma-ci-sa"

service:
  type: LoadBalancer # ClusterIP, NodePort, LoadBalancer
  annotations:
    external-dns.alpha.kubernetes.io/hostname: common-dev.gcp.milaboratories.com

env:
  secretVariables:
    - name: PL_LICENSE
      secretKeyRef:
        name: pl-license-secret
        key: pl-license-key

deployment:
  redeployOnUpgrade: true

logging:
  destination: "dir:///var/log/platforma"
  persistence:
    enabled: true

persistence:
  mainRoot:
    name: "nfs-volume"
    dataPath: "dev/common"
    workDirName: "work"
    packagesDirName: "packages"
    mountPath: /data/nfs
    existingClaim: "filestore-ci-fast-pvc"
    initDirsChown: false

  dbDir:
    enabled: true
    storageClass: "standard-rwo"
    mountPath: /data/rocksdb

artifactRegistry: "https://mi-test-assets.storage.googleapis.com/pub/assets/"

gcp:
  gar: "europe-west3-docker.pkg.dev/mik8s-euwe3-prod-gke-project/pl-containers/milaboratories/pl-containers"
  serviceAccount: "mik8s-platforma-ci-access@mik8s-euwe3-prod-gke-project.iam.gserviceaccount.com"
  projectId: "mik8s-euwe3-prod-gke-project"

primaryStorage:
  s3:
    enabled: false

  gcs:
    enabled: true
    url: "gs://mik8s-platforma-ci-euwe3-dev-gke/dev/common/primary/" # e.g., gs://<bucket>[/<prefix-in-bucket>]

dataLibrary:
  s3:
    - id: "library"
      enabled: false

  gcs:
    - id: "library"
      enabled: true
      url: "gs://mik8s-platforma-library-euwe3-prod-gke/"
    - id: "test-assets"
      enabled: true
      url: "gs://mik8s-platforma-ci-euwe3-dev-gke/test-assets/"

authOptions:
  ldap:
    enabled: false
    server: "ldap://pl0-glauth.prod-pl0.svc.cluster.local:3893"
    dn: "cn=%u,ou=users,ou=users,dc=pldemo,dc=io"

extraArgs:
  # - --skip-extended-self-check
  # - --auth-sessions-gen=1
  - --google-batch-job-dump-configs=/data/nfs/dev/common/google-batch-job-dump-configs
  - --queue-runner=ui-tasks:k8s
  - --queue-runner=light:k8s
  - --queue-runner=medium:k8s
  - --queue-runner=heavy:k8s
  - --k8s-max-cpu-request=8
  - --k8s-max-ram-request=32Gi

k8s:
  enabled: true


# googleBatch:
#   enabled: true
#   region: "europe-west3"
  
#   network: "projects/mik8s-euwe3-prod-gke-project/global/networks/mik8s-euwe3-prod-gke-vpc"
#   subnetwork: "projects/mik8s-euwe3-prod-gke-project/regions/europe-west3/subnetworks/mik8s-euwe3-prod-gke-private-1"

#   storage: "/data/nfs=nfs://10.244.108.130/nfs_share"
#   volumes:
#     enabled: true
#     name: "nfs-volume"
#     mountPath: "/data/nfs"
#     workDirName: "dev/common/work"
#     packagesDirName: "dev/common/packages"
#     existingClaim: "filestore-ci-fast-pvc"

#   jobNamePrefix: "dev-common"
#   jobImage: ""
#   provisioning: "SPOT"
#   customJobTemplate:
#     enabled: true
#     inline: |
#         {{- /* Subtemplates for items */ -}}
#         {{- define "RunnableItem" -}}
#         {
#           "script": {
#               "text": {{ printf "%q" .Script.Text }}
#           },
#           "environment": {
#               "variables": {
#                   {{- $ss := "" -}} {{- /* ss is array separator */ -}}
#                   {{- range $k, $v := .Environment.Variables -}}
#                       {{$ss}}{{ printf "%q" $k }}: {{ printf "%q" $v }}
#                       {{$ss = ","}} {{- /* ss is array separator */ -}}
#                   {{- end -}}
#               },
#               "secretVariables": {
#                   {{- $ss := "" -}}
#                   {{- range $k, $v := .Environment.SecretVariables -}}
#                       {{$ss}}{{ printf "%q" $k }}: {{ printf "%q" $v }}
#                       {{$ss = ","}} {{- /* ss is array separator */ -}}
#                   {{- end -}}
#               }
#           }
#         }
#         {{- end -}}

#         {{- define "VolumeItem" -}}
#         {
#           "nfs": {
#               "server": {{ printf "%q" .NFS.Server }},
#               "remotePath": {{ printf "%q" .NFS.RemotePath }},
#               {{if .NFS.MountOptions}}
#                 "mountOptions": {{ printf "%q" .NFS.MountOptions }}
#               {{end}}
#           },
#           "mountPath": {{ printf "%q" .MountPath }},
#           {{if .MountOptions}}
#             "mountOptions": {{ printf "%q" .MountOptions }}
#           {{end}}
#         }
#         {{- end -}}

#         {{- define "TaskGroupItem" -}}
#         {
#         "taskSpec": {
#           "runnables": [
#               {{- $ss := "" -}}
#               {{- range .TaskSpec.Runnables -}}
#               {{$ss}}{{ template "RunnableItem" . }}
#               {{- $ss = ","}} {{- /* ss is array separator */ -}}
#               {{- end -}}
#           ],
#           "computeResource": {
#               "cpuMilli": {{ .TaskSpec.ComputeResource.CPUMilli }},
#               "memoryMib": {{ .TaskSpec.ComputeResource.MemoryMib }}
#           },
#           "volumes": [
#               {{- $ss := "" -}}
#               {{- range .TaskSpec.Volumes -}}
#               {{$ss}}{{ template "VolumeItem" . }}
#               {{- $ss = ","}} {{- /* ss is array separator */ -}}
#               {{- end -}}
#           ],
#           "maxRetryCount": {{ .TaskSpec.MaxRetryCount }},
#           "maxRunDuration": {{ printf "%q" .TaskSpec.MaxRunDuration }}
#         },
#         "taskCount": {{ .TaskCount }},
#         "parallelism": {{ .Parallelism }},
#         "runAsNonRoot": {{ .RunAsNonRoot }}
#         }
#         {{- end -}}

#         {{- define "NetworkInterfaceItem" -}}
#         {
#           "network": {{ printf "%q" .Network }},
#           "subnetwork": {{ printf "%q" .Subnetwork }}
#         }
#         {{- end -}}

#         {{- define "InstanceItem" -}}
#         {
#           "policy": {
#               "bootDisk": {
#                   "image": {{ printf "%q" .Policy.BootDisk.Image }}
#               },
#               "machineType": {{ printf "%q" .Policy.MachineType }},
#               "provisioningModel": {{ printf "%q" .Policy.ProvisioningModel }}
#           }
#         }
#         {{- end -}}

#         {
#           "taskGroups": [
#               {{- $ss := "" -}}
#               {{- range .TaskGroups -}}
#               {{$ss}}{{ template "TaskGroupItem" . }}
#               {{- $ss = ","}} {{- /* ss is array separator */ -}}
#               {{- end -}}
#           ],
#           "allocationPolicy": {
#               "network": {
#                   "networkInterfaces": [ {{- $ss := "" -}}
#                   {{- range .AllocationPolicy.Network.NetworkInterfaces -}}
#                   {{$ss}}{{ template "NetworkInterfaceItem" . }}
#                   {{- $ss = ","}} {{- /* ss is array separator */ -}}
#                   {{- end -}} ]
#               },
#               "instances": [
#                   {{- $ss := "" -}}
#                   {{- range .AllocationPolicy.Instances -}}
#                   {{$ss}}{{ template "InstanceItem" . }}
#                   {{- $ss = ","}} {{- /* ss is array separator */ -}}
#                   {{- end -}}
#               ],
#               "serviceAccount": {
#                   "email": {{ printf "%q" .AllocationPolicy.ServiceAccount.Email }}
#               }
#           },
#           "labels": {
#               {{- $ss := "" -}}
#               {{- range $k, $v := .Labels -}}
#               {{$ss}}{{ printf "%q" $k }}: {{ printf "%q" $v }}
#               {{- $ss = ","}} {{- /* ss is array separator */ -}}
#               {{- end -}}
#           },
#           "logsPolicy": {
#               "destination": {{ printf "%q" .LogsPolicy.Destination }}
#           }
#         }

monitoring:
  enabled: true

debug:
  enabled: true

# -- If you are struggling with the computer use either medium (4 cpu 16 gb) or large (8 cpu 32 gb)
#  nodeSelector:
#    node.milab.io/pool: large
#  tolerations:
#    - key: "dedicated"
#      operator: "Equal"
#      value: "large"
#      effect: "NoSchedule"

# Toleration - allows pod to schedule on tainted nodes
tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "large"
    effect: "NoSchedule"

# Affinity - ensures pod schedules ONLY on large-pool nodes
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: "node.milab.io/pool"
              operator: "In"
              values:
                - "large"
securityContext:
  runAsUser: 1010
  runAsGroup: 1010
  podSecurityContext:
    fsGroup: 1010
probes:
  liveness:
    enabled: true
    # -- Type of probe. Can be 'httpGet', 'tcpSocket', or 'grpc'.
    type: grpc
    # -- Common probe settings
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 6
    # -- Configuration for httpGet probe
    httpGet:
      path: /health
      port: 8080 # Port for httpGet probe
    # -- Configuration for tcpSocket probe
    tcpSocket:
      port: 6345 # Port for tcpSocket probe
    # -- Configuration for grpc probe
    grpc:
      port: 6345 # Port for gRPC probe
      # -- Service name for gRPC probe. Required for headless services.
      service: ""
  readiness:
    enabled: true
    # -- Type of probe. Can be 'httpGet', 'tcpSocket', or 'grpc'.
    type: grpc
    # -- Common probe settings
    initialDelaySeconds: 30
    periodSeconds: 5
    timeoutSeconds: 60
    successThreshold: 1
    failureThreshold: 6
    # -- Configuration for httpGet probe
    httpGet:
      path: /health
      port: 8080 # Port for httpGet probe
    # -- Configuration for tcpSocket probe
    tcpSocket:
      port: 6345 # Port for tcpSocket probe
    # -- Configuration for grpc probe
    grpc:
      port: 6345 # Port for gRPC probe
      # -- Service name for gRPC probe. Required for headless services.
      service: ""