# Proves local.auth_providers combines every configured source, admin last,
# and that the per-source required-field checks read the resolved set.
#
# Variable values come from *.auto.tfvars.json placed next to the module by
# test-sso-tfvars.sh (generated by install.sh), so every run block below pins
# the whole auth variable set itself rather than trusting the installer's
# defaults for it.

mock_provider "google" {}
mock_provider "google-beta" {}
mock_provider "kubernetes" {}
mock_provider "helm" {}
mock_provider "kubectl" {}
mock_provider "http" {}
mock_provider "random" {}

variables {
  appwrapper_install_yaml_sha256 = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
}

override_data {
  target = data.http.appwrapper_manifest
  values = {
    response_body = ""
  }
}

override_data {
  target = data.kubectl_file_documents.appwrapper
  values = {
    documents = []
    manifests = {
      "/api/v1/namespaces/appwrapper-system" = "apiVersion: v1\nkind: Namespace\nmetadata:\n  name: appwrapper-system\n"
    }
  }
}

override_data {
  target = data.google_filestore_instance.workspace
  values = {
    file_shares = [{
      name               = "share"
      capacity_gb        = 1024
      nfs_export_options = []
      source_backup      = ""
    }]
    networks = [{
      ip_addresses      = ["10.0.0.2"]
      connect_mode      = "DIRECT_PEERING"
      modes             = ["MODE_IPV4"]
      network           = "default"
      reserved_ip_range = ""
    }]
  }
}

override_data {
  target = data.google_secret_manager_secret_version.master_secret
  values = {
    secret_data = "MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDE="
  }
}

run "combination_advertises_every_source_admin_last" {
  command = plan

  variables {
    auth_method          = ""
    sso_provider         = "google"
    google_client_id     = "combo-client-id"
    google_client_secret = "combo-client-secret"
    ldap_server          = "ldaps://ldap.example.com:636"
    ldap_search_password = "search-pw"
    enable_local_users   = true
    htpasswd_content     = "combo:$apr1$hash"
    sso_admin_users      = ""
    ldap_admin_users     = ""
    local_admin_users    = ""
  }

  assert {
    condition     = [for p in local.auth_providers : p.name] == ["google", "corp", "local", "admin"]
    error_message = "combined config must advertise google, corp, local, admin in that order"
  }

  assert {
    condition     = [for p in local.auth_providers : p.type] == ["sso", "ldap", "htpasswd", "htpasswd"]
    error_message = "each source's provider type must match its slot"
  }

  assert {
    condition     = length(kubernetes_secret.sso_client_secret) == 1 && length(kubernetes_secret.ldap_search_password) == 1 && length(kubernetes_secret.htpasswd_provided) == 1
    error_message = "all three auth Secrets must be created when every source is configured"
  }

  assert {
    condition     = one([for p in local.auth_providers : p if p.type == "ldap"]).ldap.bindPasswordSecretRef == { name = "platforma-ldap-search-password", key = "password" }
    error_message = "the corp entry must name its bind password by bindPasswordSecretRef"
  }
}

run "admin_floor_alone_when_nothing_is_set" {
  command = plan

  variables {
    auth_method        = ""
    sso_provider       = "none"
    ldap_server        = ""
    enable_local_users = false
    htpasswd_content   = ""
    sso_admin_users    = ""
    ldap_admin_users   = ""
    local_admin_users  = ""
  }

  assert {
    condition     = length(local.auth_providers) == 1 && local.auth_providers[0].name == "admin"
    error_message = "with no source configured, the admin floor must be the only entry"
  }

  assert {
    condition     = local.auth_providers[0].title == "Administrator" && local.auth_providers[0].adminUsers == [var.admin_username]
    error_message = "the admin entry must carry the Administrator title and grant admin_username"
  }

  assert {
    condition     = length(local.auth_providers[0].htpasswd.credentials) == 1 && local.auth_providers[0].htpasswd.credentials[0].username == var.admin_username
    error_message = "the admin entry must carry one inline credential for admin_username"
  }

  assert {
    condition     = length(kubernetes_secret.htpasswd_provided) == 0 && length(kubernetes_secret.ldap_search_password) == 0 && length(kubernetes_secret.sso_client_secret) == 0
    error_message = "no auth Secret should be created when no source is configured"
  }
}

run "htpasswd_file_advertised_only_through_enable_local_users" {
  command = plan

  variables {
    auth_method        = ""
    sso_provider       = "none"
    ldap_server        = ""
    enable_local_users = true
    htpasswd_content   = "local:$apr1$hash"
    sso_admin_users    = ""
    ldap_admin_users   = ""
    local_admin_users  = ""
  }

  assert {
    condition     = [for p in local.auth_providers : p.name] == ["local", "admin"]
    error_message = "enable_local_users must advertise the local source, then admin"
  }

  assert {
    condition     = length(kubernetes_secret.htpasswd_provided) == 1
    error_message = "the htpasswd Secret must be created for the local source"
  }
}

run "htpasswd_file_ignored_by_a_legacy_selector_that_did_not_choose_it" {
  command = plan

  variables {
    auth_method          = "google"
    sso_provider         = "none"
    google_client_id     = "legacy-client-id"
    google_client_secret = "legacy-client-secret"
    ldap_server          = ""
    enable_local_users   = false
    htpasswd_content     = "orphan:$apr1$hash"
    sso_admin_users      = ""
    ldap_admin_users     = ""
    local_admin_users    = ""
  }

  assert {
    condition     = [for p in local.auth_providers : p.name] == ["google", "admin"]
    error_message = "a legacy google selector must ignore an htpasswd_content nobody advertised"
  }
}

run "admin_regexps_land_under_their_own_source" {
  command = plan

  variables {
    auth_method          = ""
    sso_provider         = "google"
    google_client_id     = "regexp-client-id"
    google_client_secret = "regexp-client-secret"
    ldap_server          = "ldaps://ldap.example.com:636"
    ldap_search_password = "search-pw"
    enable_local_users   = true
    htpasswd_content     = "regexp:$apr1$hash"
    sso_admin_users      = "alice@example.com;^ops-.*$"
    ldap_admin_users     = "svc-admin"
    local_admin_users    = ""
  }

  assert {
    condition     = one([for p in local.auth_providers : p if p.type == "sso"]).roles.attrRegexps == ["admin=login=alice@example.com", "admin=login=^ops-.*$"]
    error_message = "the SSO entry must carry sso_admin_users as attrRegexps"
  }

  assert {
    condition     = one([for p in local.auth_providers : p if p.type == "ldap"]).roles.attrRegexps == ["admin=login=svc-admin"]
    error_message = "the corp entry must carry ldap_admin_users as attrRegexps"
  }

  assert {
    condition     = !contains(keys(one([for p in local.auth_providers : p if p.name == "local"])), "roles")
    error_message = "the local entry must carry no roles key when local_admin_users is empty"
  }

  assert {
    condition     = !contains(keys(one([for p in local.auth_providers : p if p.name == "admin"])), "roles")
    error_message = "the admin entry grants by adminUsers, never by roles"
  }
}

run "admin_regexps_trim_spaces_and_drop_the_trailing_empty_pattern" {
  command = plan

  variables {
    auth_method          = ""
    sso_provider         = "google"
    google_client_id     = "trim-client-id"
    google_client_secret = "trim-client-secret"
    ldap_server          = ""
    enable_local_users   = false
    htpasswd_content     = ""
    sso_admin_users      = " alice@example.com ; ^ops-.*$ ; "
    ldap_admin_users     = ""
    local_admin_users    = ""
  }

  assert {
    condition     = one([for p in local.auth_providers : p if p.type == "sso"]).roles.attrRegexps == ["admin=login=alice@example.com", "admin=login=^ops-.*$"]
    error_message = "surrounding spaces and a trailing semicolon must not add an empty or unspaced pattern"
  }
}

run "legacy_selector_ldap_configures_one_source" {
  command = plan

  variables {
    auth_method        = "ldap"
    sso_provider       = "none"
    ldap_server        = "ldaps://ldap.example.com:636"
    enable_local_users = false
    htpasswd_content   = ""
    sso_admin_users    = ""
    ldap_admin_users   = ""
    local_admin_users  = ""
  }

  assert {
    condition     = [for p in local.auth_providers : p.name] == ["corp", "admin"]
    error_message = "auth_method=ldap must advertise corp then admin"
  }
}

run "legacy_selector_google_configures_one_source" {
  command = plan

  variables {
    auth_method          = "google"
    sso_provider         = "none"
    google_client_id     = "legacy-google-id"
    google_client_secret = "legacy-google-secret"
    ldap_server          = ""
    enable_local_users   = false
    htpasswd_content     = ""
    sso_admin_users      = ""
    ldap_admin_users     = ""
    local_admin_users    = ""
  }

  assert {
    condition     = [for p in local.auth_providers : p.name] == ["google", "admin"]
    error_message = "auth_method=google must advertise google then admin"
  }

  assert {
    condition     = length(kubernetes_secret.sso_client_secret) == 1
    error_message = "the sso_client_secret Secret must be created for the legacy google selector"
  }
}

run "legacy_selector_htpasswd_configures_one_source" {
  command = plan

  variables {
    auth_method        = "htpasswd"
    sso_provider       = "none"
    ldap_server        = ""
    enable_local_users = false
    htpasswd_content   = "legacy:$apr1$hash"
    sso_admin_users    = ""
    ldap_admin_users   = ""
    local_admin_users  = ""
  }

  assert {
    condition     = [for p in local.auth_providers : p.name] == ["local", "admin"]
    error_message = "auth_method=htpasswd must advertise local then admin"
  }
}

run "legacy_selector_rejects_an_unknown_value" {
  command = plan

  variables {
    auth_method        = "nonsense"
    sso_provider       = "none"
    ldap_server        = ""
    enable_local_users = false
    htpasswd_content   = ""
    sso_admin_users    = ""
    ldap_admin_users   = ""
    local_admin_users  = ""
  }

  expect_failures = [var.auth_method]
}

run "legacy_selector_accepts_empty" {
  command = plan

  variables {
    auth_method        = ""
    sso_provider       = "none"
    ldap_server        = ""
    enable_local_users = false
    htpasswd_content   = ""
    sso_admin_users    = ""
    ldap_admin_users   = ""
    local_admin_users  = ""
  }

  assert {
    condition     = local.auth_sources.sso == ""
    error_message = "an empty auth_method must select no SSO source"
  }
}

run "legacy_google_selector_ignores_a_leftover_ldap_server" {
  command = plan

  variables {
    auth_method          = "google"
    sso_provider         = "none"
    google_client_id     = "leftover-ldap-id"
    google_client_secret = "leftover-ldap-secret"
    ldap_server          = "ldaps://ldap.example.com:636"
    enable_local_users   = false
    htpasswd_content     = ""
    sso_admin_users      = ""
    ldap_admin_users     = ""
    local_admin_users    = ""
  }

  assert {
    condition     = [for p in local.auth_providers : p.name] == ["google", "admin"]
    error_message = "a legacy google selector must not also advertise corp from a leftover ldap_server"
  }

  assert {
    condition     = length(kubernetes_secret.ldap_search_password) == 0
    error_message = "the ldap_search_password Secret must not be created when corp is not advertised"
  }
}

run "sso_required_field_check_reads_sso_provider_google" {
  command = plan

  variables {
    auth_method        = ""
    sso_provider       = "google"
    google_client_id   = ""
    ldap_server        = ""
    enable_local_users = false
    htpasswd_content   = ""
    sso_admin_users    = ""
    ldap_admin_users   = ""
    local_admin_users  = ""
  }

  expect_failures = [helm_release.platforma[0]]
}

run "sso_required_field_check_reads_sso_provider_entra" {
  command = plan

  variables {
    auth_method        = ""
    sso_provider       = "entra"
    entra_tenant_id    = ""
    ldap_server        = ""
    enable_local_users = false
    htpasswd_content   = ""
    sso_admin_users    = ""
    ldap_admin_users   = ""
    local_admin_users  = ""
  }

  expect_failures = [helm_release.platforma[0]]
}

run "sso_required_field_check_reads_sso_provider_oidc" {
  command = plan

  variables {
    auth_method        = ""
    sso_provider       = "oidc"
    oidc_issuer        = ""
    ldap_server        = ""
    enable_local_users = false
    htpasswd_content   = ""
    sso_admin_users    = ""
    ldap_admin_users   = ""
    local_admin_users  = ""
  }

  expect_failures = [helm_release.platforma[0]]
}
