# Proves the five migration refusals in helm_release.platforma's lifecycle
# block fire on the input each one guards, and pass on the control beside it.
#
# Variable values come from *.auto.tfvars.json placed next to the module by
# test-sso-tfvars.sh (generated by install.sh), so every run block below pins
# the whole auth variable set itself rather than trusting the installer's
# defaults for it.

mock_provider "google" {}
mock_provider "google-beta" {}
mock_provider "kubernetes" {}
mock_provider "helm" {}
mock_provider "kubectl" {}
mock_provider "http" {}
mock_provider "random" {}

variables {
  appwrapper_install_yaml_sha256 = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
}

override_data {
  target = data.http.appwrapper_manifest
  values = {
    response_body = ""
  }
}

override_data {
  target = data.kubectl_file_documents.appwrapper
  values = {
    documents = []
    manifests = {
      "/api/v1/namespaces/appwrapper-system" = "apiVersion: v1\nkind: Namespace\nmetadata:\n  name: appwrapper-system\n"
    }
  }
}

override_data {
  target = data.google_filestore_instance.workspace
  values = {
    file_shares = [{
      name               = "share"
      capacity_gb        = 1024
      nfs_export_options = []
      source_backup      = ""
    }]
    networks = [{
      ip_addresses      = ["10.0.0.2"]
      connect_mode      = "DIRECT_PEERING"
      modes             = ["MODE_IPV4"]
      network           = "default"
      reserved_ip_range = ""
    }]
  }
}

override_data {
  target = data.google_secret_manager_secret_version.master_secret
  values = {
    secret_data = "MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDE="
  }
}

run "legacy_selector_refused_beside_sso_provider" {
  command = plan

  variables {
    auth_method          = "google"
    google_client_id     = "legacy-combo-id"
    google_client_secret = "legacy-combo-secret"
    sso_provider         = "google"
    ldap_server          = ""
    enable_local_users   = false
    htpasswd_content     = ""
    sso_admin_users      = ""
    ldap_admin_users     = ""
    local_admin_users    = ""
  }

  expect_failures = [helm_release.platforma[0]]
}

run "legacy_selector_refused_beside_ldap_admin_users" {
  command = plan

  variables {
    auth_method        = "ldap"
    sso_provider       = "none"
    ldap_server        = "ldaps://ldap.example.com:636"
    enable_local_users = false
    htpasswd_content   = ""
    sso_admin_users    = ""
    ldap_admin_users   = "svc-admin"
    local_admin_users  = ""
  }

  expect_failures = [helm_release.platforma[0]]
}

run "legacy_selector_beside_a_leftover_ldap_server_passes" {
  command = plan

  variables {
    auth_method          = "google"
    google_client_id     = "leftover-ldap-id"
    google_client_secret = "leftover-ldap-secret"
    sso_provider         = "none"
    ldap_server          = "ldaps://ldap.example.com:636"
    enable_local_users   = false
    htpasswd_content     = ""
    sso_admin_users      = ""
    ldap_admin_users     = ""
    local_admin_users    = ""
  }

  assert {
    condition     = [for p in local.auth_providers : p.name] == ["google", "admin"]
    error_message = "ldap_server is not in the conflict set, so a legacy google selector beside it must plan"
  }
}

run "leftover_admin_user_flag_with_value_refused" {
  command = plan

  variables {
    auth_method           = ""
    sso_provider          = "none"
    ldap_server           = ""
    enable_local_users    = false
    htpasswd_content      = ""
    sso_admin_users       = ""
    ldap_admin_users      = ""
    local_admin_users     = ""
    additional_extra_args = ["--admin-user=alice"]
  }

  expect_failures = [helm_release.platforma[0]]
}

run "leftover_admin_user_flag_bare_refused" {
  command = plan

  variables {
    auth_method           = ""
    sso_provider          = "none"
    ldap_server           = ""
    enable_local_users    = false
    htpasswd_content      = ""
    sso_admin_users       = ""
    ldap_admin_users      = ""
    local_admin_users     = ""
    additional_extra_args = ["--admin-user"]
  }

  expect_failures = [helm_release.platforma[0]]
}

run "an_unrelated_extra_arg_passes" {
  command = plan

  variables {
    auth_method           = ""
    sso_provider          = "none"
    ldap_server           = ""
    enable_local_users    = false
    htpasswd_content      = ""
    sso_admin_users       = ""
    ldap_admin_users      = ""
    local_admin_users     = ""
    additional_extra_args = ["--default-docker-registry=x"]
  }

  assert {
    condition     = length(local.auth_providers) == 1
    error_message = "an unrelated extra arg must not be treated as a leftover admin flag"
  }
}

run "local_users_without_htpasswd_content_refused" {
  command = plan

  variables {
    auth_method        = ""
    sso_provider       = "none"
    ldap_server        = ""
    enable_local_users = true
    htpasswd_content   = ""
    sso_admin_users    = ""
    ldap_admin_users   = ""
    local_admin_users  = ""
  }

  expect_failures = [helm_release.platforma[0]]
}

run "local_users_with_htpasswd_content_passes" {
  command = plan

  variables {
    auth_method        = ""
    sso_provider       = "none"
    ldap_server        = ""
    enable_local_users = true
    htpasswd_content   = "alice:$apr1$hash"
    sso_admin_users    = ""
    ldap_admin_users   = ""
    local_admin_users  = ""
  }

  assert {
    condition     = [for p in local.auth_providers : p.name] == ["local", "admin"]
    error_message = "enable_local_users with htpasswd_content set must plan"
  }
}

run "orphan_htpasswd_content_refused" {
  command = plan

  variables {
    auth_method        = ""
    sso_provider       = "none"
    ldap_server        = ""
    enable_local_users = false
    htpasswd_content   = "orphan:$apr1$hash"
    sso_admin_users    = ""
    ldap_admin_users   = ""
    local_admin_users  = ""
  }

  expect_failures = [helm_release.platforma[0]]
}

run "htpasswd_content_ignored_by_a_legacy_selector_passes" {
  command = plan

  variables {
    auth_method          = "google"
    google_client_id     = "orphan-ok-id"
    google_client_secret = "orphan-ok-secret"
    sso_provider         = "none"
    ldap_server          = ""
    enable_local_users   = false
    htpasswd_content     = "orphan:$apr1$hash"
    sso_admin_users      = ""
    ldap_admin_users     = ""
    local_admin_users    = ""
  }

  assert {
    condition     = [for p in local.auth_providers : p.name] == ["google", "admin"]
    error_message = "a legacy selector that already ignores htpasswd_content must plan"
  }
}

run "sso_admin_users_for_a_disabled_sso_source_refused" {
  command = plan

  variables {
    auth_method        = ""
    sso_provider       = "none"
    ldap_server        = ""
    enable_local_users = false
    htpasswd_content   = ""
    sso_admin_users    = "alice@example.com"
    ldap_admin_users   = ""
    local_admin_users  = ""
  }

  expect_failures = [helm_release.platforma[0]]
}

run "ldap_admin_users_for_a_disabled_ldap_source_refused" {
  command = plan

  variables {
    auth_method        = ""
    sso_provider       = "none"
    ldap_server        = ""
    enable_local_users = false
    htpasswd_content   = ""
    sso_admin_users    = ""
    ldap_admin_users   = "svc-admin"
    local_admin_users  = ""
  }

  expect_failures = [helm_release.platforma[0]]
}

run "local_admin_users_for_a_disabled_local_source_refused" {
  command = plan

  variables {
    auth_method        = ""
    sso_provider       = "none"
    ldap_server        = ""
    enable_local_users = false
    htpasswd_content   = ""
    sso_admin_users    = ""
    ldap_admin_users   = ""
    local_admin_users  = "ops"
  }

  expect_failures = [helm_release.platforma[0]]
}

