# Proves the Google-SSO client-secret value flow WITHOUT a cluster:
#   var.google_client_secret -> kubernetes_secret.sso_client_secret
#                             -> local.auth_helm_value.sso.clientSecret.secretName
# Providers are mocked; the appwrapper http/kubectl data sources are overridden
# so the mocked plan doesn't choke on unknown for_each keys.
#
# Variable values come from *.auto.tfvars.json placed next to the module by
# test-sso-tfvars.sh (generated by install.sh), so this asserts on the exact
# tfvars install.sh produces.

mock_provider "google" {}
mock_provider "google-beta" {}
mock_provider "kubernetes" {}
mock_provider "helm" {}
mock_provider "kubectl" {}
mock_provider "http" {}
mock_provider "random" {}

run "google_sso_wires_client_secret" {
  command = plan

  # Empty upstream manifest → its SHA-256 is deterministic, so the appwrapper
  # integrity postcondition passes without a real download.
  variables {
    appwrapper_install_yaml_sha256 = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
  }

  override_data {
    target = data.http.appwrapper_manifest
    values = {
      response_body = ""
    }
  }

  # Keep only the namespace manifest (indexed directly by helm.tf); the
  # for_each over the rest then resolves to empty.
  override_data {
    target = data.kubectl_file_documents.appwrapper
    values = {
      documents = []
      manifests = {
        "/api/v1/namespaces/appwrapper-system" = "apiVersion: v1\nkind: Namespace\nmetadata:\n  name: appwrapper-system\n"
      }
    }
  }

  # helm.tf indexes file_shares[0]/networks[0].ip_addresses[0]; mock returns
  # empty lists, so supply the indexed elements.
  override_data {
    target = data.google_filestore_instance.workspace
    values = {
      file_shares = [{
        name               = "share"
        capacity_gb        = 1024
        nfs_export_options = []
        source_backup      = ""
      }]
      networks = [{
        ip_addresses      = ["10.0.0.2"]
        connect_mode      = "DIRECT_PEERING"
        modes             = ["MODE_IPV4"]
        network           = "default"
        reserved_ip_range = ""
      }]
    }
  }

  # Mocked Secret Manager returns a random string; supply a valid base64 value
  # (>= 32 raw bytes) so the master-secret precondition passes.
  override_data {
    target = data.google_secret_manager_secret_version.master_secret
    values = {
      secret_data = "MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDE="
    }
  }

  assert {
    condition     = local.auth_helm_value.sso.clientSecret.secretName == "platforma-sso-client-secret"
    error_message = "google_client_secret did not map to auth_helm_value.sso.clientSecret.secretName"
  }

  assert {
    condition     = local.auth_helm_value.sso.accessType == "offline"
    error_message = "google preset must set accessType=offline so Google issues a refresh token"
  }

  assert {
    condition     = length(kubernetes_secret.sso_client_secret) == 1
    error_message = "kubernetes_secret.sso_client_secret was not created for google auth"
  }

  assert {
    condition     = kubernetes_secret.sso_client_secret[0].metadata[0].name == "platforma-sso-client-secret"
    error_message = "sso secret has the wrong name"
  }

  assert {
    condition     = kubernetes_secret.sso_client_secret[0].data["client-secret"] == var.google_client_secret
    error_message = "sso secret value does not equal var.google_client_secret"
  }
}
