apiVersion: v2
name: platforma
description: Platforma - Bioinformatics platform for Kubernetes
type: application
version: 3.0.0-rc.6
appVersion: "1.45.3"
kubeVersion: ">=1.28.0-0"

keywords:
  - platforma
  - bioinformatics
  - kubernetes
  - kueue

home: https://platforma.bio
sources:
  - https://github.com/milaboratory/platforma-helm

maintainers:
  - name: MiLaboratories
    email: support@milaboratories.com

annotations:
  artifacthub.io/license: Proprietary
  artifacthub.io/operator: "false"
