apiVersion: v2
name: platforma
description: Platforma - Bioinformatics platform for Kubernetes
type: application
version: 3.0.0
appVersion: "1.45.3"
kubeVersion: ">=1.28.0-0"

keywords:
  - platforma
  - bioinformatics
  - kubernetes
  - kueue

home: https://platforma.bio
sources:
  - https://github.com/milaboratory/platforma-helm

maintainers:
  - name: MiLaboratories
    email: support@milaboratories.com

annotations:
  artifacthub.io/license: Proprietary
  artifacthub.io/operator: "false"

dependencies:
  - name: cluster-autoscaler
    version: "9.55.1"
    repository: "https://kubernetes.github.io/autoscaler"
    condition: cluster-autoscaler.enabled
  - name: aws-load-balancer-controller
    version: "1.17.1"
    repository: "https://aws.github.io/eks-charts"
    condition: aws-load-balancer-controller.enabled
  - name: external-dns
    version: "1.20.0"
    repository: "https://kubernetes-sigs.github.io/external-dns/"
    condition: external-dns.enabled
